PSAPI_RestaurantSystem/Models/ViewModels/AddOrderedMealViewModel.cs
using PSAPIRestaurantSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PSAPIRestaurantSystem.Models.ViewModels
{
    public class AddOrderedMealViewModel
    {
        public int? OrderId { get; set; }
        public int? CurrentOrderedMealId { get; set; }
        public int? Quantity { get; set; }
        public string Comments { get; set; } = "";
        public DateTime OrderedForDate { get; set; }
        public List<OrderedMeal> OrderedMeals { get; set; }
    }
}

PSAPI_RestaurantSystem/Models/Waiter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PSAPIRestaurantSystem.Models
{
    public class Waiter
    {
        [Key]
        public int WaiterId { get; set; }

        [Required] 
        public double Tips { get; set; }


        // Relationships
        // Employee to waiter (1 to 1)
        public int EmployeeId { get; set; }
        public Employee Employee { get; set; }

        // Waiter to order (1 to *)
        [InverseProperty("ManagedBy")]
        public List<Order> Orders { get; set; }

        // Waiter to takeoutorder (1 to *)
        [InverseProperty("ManagedBy")]
        public List<TakeoutOrder> TakeoutOrders { get; set; }
    }
}

PSAPI_RestaurantSystem/Controllers/WaiterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PSAPIRestaurantSystem.Models;
using PSAPIRestaurantSystem.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace PSAPIRestaurantSystem.Controllers
{
    public class WaiterController : Controller
    {
        private readonly RestaurantContext _context;
        private readonly ILogger<WaiterController> _logger;
        public WaiterController(RestaurantContext context, ILogger<WaiterController> logger)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult WaiterReservationPage()
        {
            var reserv = _context.Reservations
                .Include(r => r.ReservedBy)
                    .ThenInclude(p => p.Person)
                    .Include(t => t.TableOccupancies).ToList();
            return View(reserv);
        }

        // Open orders page
        public IActionResult OrderList()
        {
            var orders = _context.Orders
                .Include(t => t.TableOccupancies)
                .Include(o => o.OrderedMeals)
                .Include(m => m.ManagedBy)
                    .ThenInclude(e => e.Employee)
                        .ThenInclude(u => u.User)
                            .ThenInclude(p => p.Person).ToList();

            foreach (var order in orders)
            {
                if(order.State == (int)OrderState.Created || order.State == (int)OrderState.CreatedReservation)
                {
                    if(order.OrderedMeals.Count > 0)
                        order.Duration = (int)(DateTime.Now - order.OrderDate).TotalMinutes;
                }
                order.Price = order.OrderedMeals.Sum(s => s.Price * s.Quantity);
            }
            return View(orders);
        }

        // Order creation for GET
        public IActionResult OrderCreationForm()
        {
            ViewData["TableNum"] = new SelectList(_context.Tables, "TableNum", "TableNum");
            return View();
        }

        // Order creation form, add table to list and returns page with new list POST
        [HttpPost]
        public IActionResult OrderCreationFormAdd(OrderCreateViewModel model)
        {
            if (model.Tables == null) model.Tables = new List<Table>();
            var table = _context.Tables.Find(model.CurrentTable);
            model.Tables.Add(table);
            model.CurrentTable = null;
            ViewData["TableNum"] = new SelectList(_context.Tables, "TableNum", "TableNum");
            return View("OrderCreationForm", model);
        }


        // Order creation form POST
        [HttpPost]
        public IActionResult OrderCreationForm(OrderCreateViewModel model)
        {
            if (model.Tables == null) model.Tables = new List<Table>();
            var usrID = HttpContext.Session.GetInt32("userID");
            var waiterId = _context.Users.Where(w => w.UserId == (int)usrID).Include(e => e.Employee).ThenInclude(w => w.Waiter).FirstOrDefault().Employee.Waiter.WaiterId;
            var table = _context.Tables.Find(model.CurrentTable);
            model.Tables.Add(table);
            var order = new Order { Duration = 0, ManagedByWaiterId = waiterId, OrderDate = DateTime.Now, State = (int)OrderState.Created, Price = 0.0 };
            _context.Add(order);
            _context.SaveChanges();

            foreach(var t in model.Tables)
            {
                var to = new TableOccupancy { OrderId = order.OrderId, TableId = t.TableNum };
                _context.Add(to);
            }
            _context.SaveChanges();
            return RedirectToAction("OrderList");
        }

        // Order page (Details view) GET
        public IActionResult OrderPage(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var order = _context.Orders
                .Where(o => o.OrderId == id)
                .Include(m => m.OrderedMeals)
                    .ThenInclude(e => e.MenuEntry)
                .Include(w => w.ManagedBy)
                    .ThenInclude(e => e.Employee)
                        .ThenInclude(u => u.User)
                .Include(t => t.TableOccupancies)
                .FirstOrDefault();

            order.Price = order.OrderedMeals.Sum(s => s.Price * s.Quantity);

            if (order == null)
            {
                return NotFound();
            }
                
            return View(order);
        }

        public IActionResult OrderDeleteForm(int id)
        {
            var order = _context.Orders.Find(id);
            return View(order);
        }

        // Order deletion form POST
        [HttpPost]
        public IActionResult OrderDeleteForm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = _context.Orders.Find(id);
            
            if(order == null)
            {
                return NotFound();
            }

            order.State = (int)OrderState.Canceled;
            _context.Update(order);
            _context.SaveChanges();

            return RedirectToAction("OrderList");
        }

        // AddOrderedMeals for order GET
        public IActionResult AddOrderedMeal(int id)
        {

            var model = new AddOrderedMealViewModel() { OrderId = id };
            model.OrderedMeals = new List<OrderedMeal>();
            var menuEntries = _context.MenuEntries.Include(m => m.Menu).ToList();
            var selectList = new List<SelectListItem>();

            foreach(var entry in menuEntries)
            {
                selectList.Add(new SelectListItem() { 
                    Value = entry.MenuEntryId.ToString(),
                    Text = entry.MenuEntryName,
                });;
            }
            ViewData["Menu"] = new SelectList(selectList, "Value", "Text");
            return View(model);
        }


        [HttpPost]
        public IActionResult AddOrderedMealAdd(AddOrderedMealViewModel model)
        {
            if (model.OrderedMeals == null) model.OrderedMeals = new List<OrderedMeal>();

            var meal = new OrderedMeal {
                InOrderOrderId = (int)model.OrderId,
                MenuEntryId = (int)model.CurrentOrderedMealId,
                Quantity = (int)model.Quantity,
                Comment = model.Comments,
                Price = _context.MenuEntries.Find(model.CurrentOrderedMealId).Price
                };
            model.OrderedMeals.Add(meal);
            for (int i = 0; i < model.OrderedMeals.Count; i++)
            {
                model.OrderedMeals[i].MenuEntry = _context.MenuEntries.Find(model.OrderedMeals[i].MenuEntryId);
            }
            model.CurrentOrderedMealId = null;
            model.Quantity = null;
            model.Comments = null;

            
            var menuEntries = _context.MenuEntries.Include(m => m.Menu).ToList();
            var selectList = new List<SelectListItem>();
            foreach (var entry in menuEntries)
            {
                selectList.Add(new SelectListItem()
                {
                    Value = entry.MenuEntryId.ToString(),
                    Text = entry.MenuEntryName,
                }); ;
            }
            ViewData["Menu"] = new SelectList(selectList, "Value", "Text");
            return View("AddOrderedMeal", model);
        }


        [HttpPost]
        public IActionResult AddOrderedMeal(int? id, AddOrderedMealViewModel model)
        {
            if (model.OrderedMeals == null) model.OrderedMeals = new List<OrderedMeal>();

            var meal = new OrderedMeal
            {
                InOrderOrderId = (int)model.OrderId,
                MenuEntryId = (int)model.CurrentOrderedMealId,
                Quantity = (int)model.Quantity,
                Comment = model.Comments,
                Price = _context.MenuEntries.Find(model.CurrentOrderedMealId).Price
            };
            model.OrderedMeals.Add(meal);

            foreach(var m in model.OrderedMeals)
            {
                var om = new OrderedMeal
                {
                    InOrderOrderId = (int)model.OrderId,
                    MenuEntryId = m.MenuEntryId,
                    Quantity = m.Quantity,
                    Comment = m.Comment,
                    Price = m.Price
                };
                _context.Add(om);
            }
            _context.SaveChanges();


            var menuEntries = _context.MenuEntries.Include(m => m.Menu).ToList();
            var selectList = new List<SelectListItem>();
            foreach (var entry in menuEntries)
            {
                selectList.Add(new SelectListItem()
                {
                    Value = entry.MenuEntryId.ToString(),
                    Text = entry.MenuEntryName,
                }); ;
            }
            ViewData["Menu"] = new SelectList(selectList, "Value", "Text");
            return Redirect("/Waiter/OrderPage/" + model.OrderId.ToString());
        }
    }
}

PSAPI_RestaurantSystem/Views/Waiter/AddOrderedMeal.cshtml
@model PSAPIRestaurantSystem.Models.ViewModels.AddOrderedMealViewModel

@{
    ViewData["Title"] = "Papildyti užsakymą";
}

<h1>Papildyti užsakyma</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().MenuEntryId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Quantity)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Comment)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.OrderedMeals.Count > 0)
                    {
                        @for (int i = 0; i < Model.OrderedMeals.Count; i++)
                        {
                            string menuEntry = Model.OrderedMeals[i].MenuEntry.MenuEntryName;
                            int menuEntryId = Model.OrderedMeals[i].MenuEntryId;
                            int qty = Model.OrderedMeals[i].Quantity;
                            double price = Model.OrderedMeals[i].Price;
                            string comm = Model.OrderedMeals[i].Comment;

                            <tr>
                                <td>
                                    <input style="width:150px" disabled name="OrderedMeals[i].MenuEntryId" value=@menuEntry />
                                    <input hidden asp-for="OrderedMeals[i].MenuEntryId" value=@menuEntryId />
                                </td>
                                <td>
                                    <input disabled name="OrderedMeals[i].MenuEntryId" value=@qty />
                                    <input hidden asp-for="OrderedMeals[i].Quantity" value=@qty />
                                </td>
                                <td>
                                    <input disabled name="OrderedMeals[i].MenuEntryId" value=@price />
                                    <input hidden asp-for="OrderedMeals[i].Price" value=@price />
                                </td>
                                <td>
                                    <input disabled name="OrderedMeals[i].MenuEntryId" value=@comm />
                                    <input hidden asp-for="OrderedMeals[i].Comment" value=@comm />
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>

            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @if (Model != null)
                {
                    <label asp-for="CurrentTable" class="control-label"></label>
                    @for (int i = 0; i < Model.Tables.Count; i++)
                    {
                        int tableNum = Model.Tables[i].TableNum;
                        <div class="form-group">
                            <select disabled asp-items="ViewBag.TableNum" asp-for="Tables[i].TableNum" class="control-label"></select>
                            <input hidden asp-for="Tables[i].TableNum" value=@tableNum />
                        </div>
                    }
                }*@
            <input hidden asp-for="OrderId" value="@Model.OrderId" />
            <div class="form-group">
                <label class="control-label">Pasirinkite patiekalą/gėrimą:</label>
                <select asp-for="CurrentOrderedMealId" asp-items="ViewBag.Menu" class="form-control"></select>
                <span asp-validation-for="CurrentOrderedMealId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Pasirinkite kiekį:</label>
                <input type="number" asp-for="Quantity" value="1" asp-items="ViewBag.Menu" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">Pastabos/komentarai:</label>
                <input type="text" asp-for="Comments" asp-items="ViewBag.Menu" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>

            <button type="submit" class="btn" formaction="/Waiter/AddOrderedMealAdd/@Model.OrderId"><is class="fas fa-plus"></is></button>
            <div class="form-group">
                <input type="submit" value="Išsaugoti" asp-action="AddOrderedMeal" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="OrderPage/@Model.OrderId" asp->Grįžti atgal</a>
</div>

PSAPI_RestaurantSystem/Views/Waiter/OrderCreationForm.cshtml
@model PSAPIRestaurantSystem.Models.ViewModels.OrderCreateViewModel

@{
    ViewData["Title"] = "Sukurti užsakyma";
}

<h1>Sukurti užsakyma</h1>

<h4>Pasirinkite staliukus užsakymui</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (Model != null)
            {
                <label class="control-label">Staliukas:</label>
                @for (int i = 0; i < Model.Tables.Count; i++)
                {
                    int tableNum = Model.Tables[i].TableNum;
                    <div class="form-group">
                        <select disabled asp-items="ViewBag.TableNum" asp-for="Tables[i].TableNum" class="control-label"></select>
                        <input hidden asp-for="Tables[i].TableNum" value=@tableNum />
                    </div>
                }
            }

            <div class="form-group">
                <label class="control-label">Pasirinkite staliuką:</label>
                <select asp-for="CurrentTable" asp-items="ViewBag.TableNum" class="form-control"></select>
                <span asp-validation-for="CurrentTable" class="text-danger"></span>
            </div>
            <br>
            <button type="submit" class="btn" formaction="OrderCreationFormAdd"><i class="fas fa-plus"></i></button>
            <div class="form-group">
                <input type="submit" value="Sukurti" asp-action="OrderCreationForm" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="OrderList">Grįžti atgal</a>
</div>

PSAPI_RestaurantSystem/Views/Waiter/OrderDeleteForm.cshtml
@model PSAPIRestaurantSystem.Models.Order

@{
    ViewData["Title"] = "Ištrinti užsakymą";
}

<h1>Ištrinti užsakymą</h1>

<h3>Ar tikrai norite ištrinti užsakyma Nr. @Model.OrderId?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
    </dl>
    
    <form asp-action="OrderDeleteForm">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Taip" class="btn btn-danger" />
        <input type="button" value="Ne" class="btn btn-success"  onclick="location.href='@Url.Action("OrderPage", "Waiter")/@Model.OrderId'"/>
    </form>
</div>

PSAPI_RestaurantSystem/Views/Waiter/OrderList.cshtml
@using PSAPIRestaurantSystem.Models;
@model IEnumerable<PSAPIRestaurantSystem.Models.Order>

@{
    ViewData["Title"] = "Užsakymai";
}

<h1>Užsakymai</h1>

<p>
    <a asp-controller="Waiter" asp-action="OrderCreationForm"><i class="fas fa-plus"></i>Sukurti naują užsąkymą</a>
</p>
<table class="table table-hover">
    <thead class="bg-info">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().OrderId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().ManagedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstOrDefault().Duration)
            </th>
            <th>
                Staliukai
            </th>
            <th>
            </th>
        </tr>
    </thead>

    <thead>
        <tr class="font-weight-bold" style="background:#d7dadd;">
            <th>Aktyvūs užsakymai</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            @if (item.State == (int)OrderState.Created)
            {
                var tables = String.Join(", ", item.TableOccupancies.Select(n => n.TableId.ToString()).ToArray());
                string price = item.Price.ToString("0.00");
                if (item.Price == 0)
                {
                    price = "-";
                }
                <tr style="padding-left:30px">
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Name) @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => price)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => tables)
                    </td>
                    <td>
                        <a asp-controller="Waiter" asp-action="OrderPage" asp-route-id="@item.OrderId"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        }
    </thead>

    <thead>
        <tr class="font-weight-bold" style="background:#d7dadd;">
            <th>Rezervacijų užsakymai</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            @if (item.State == (int)OrderState.CreatedReservation)
            {
                var tables = String.Join(", ", item.TableOccupancies.Select(n => n.TableId.ToString()).ToArray());
                string price = item.Price.ToString("0.00");
                if (item.Price == 0)
                {
                    price = "-";
                }
                <tr style="padding-left:30px">
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Name) @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => price)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => tables)
                    </td>
                    <td>
                        <a asp-controller="Waiter" asp-action="OrderPage" asp-route-id="@item.OrderId"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        }
    </thead>

    <thead>
        <tr class="font-weight-bold" style="background:#d7dadd;">
            <th>Atlikti užsakymai</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            @if (item.State == (int)OrderState.Paid)
            {
                var tables = String.Join(", ", item.TableOccupancies.Select(n => n.TableId.ToString()).ToArray());
                string price = item.Price.ToString("0.00");
                if (item.Price == 0)
                {
                    price = "-";
                }
                <tr style="padding-left:30px">
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Name) @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => price)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => tables)
                    </td>
                    <td>
                        <a asp-controller="Waiter" asp-action="OrderPage" asp-route-id="@item.OrderId"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        }
    </thead>

    <thead>
        <tr class="font-weight-bold" style="background:#d7dadd;">
            <th>Atšaukti užsakymai</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            @if (item.State == (int)OrderState.Canceled)
            {
                var tables = String.Join(", ", item.TableOccupancies.Select(n => n.TableId.ToString()).ToArray());
                string price = item.Price.ToString("0.00");
                if (item.Price == 0)
                {
                    price = "-";
                }
                <tr style="padding-left:30px">
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Name) @Html.DisplayFor(entryItem => item.ManagedBy.Employee.User.Person.Surname)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.OrderDate)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => price)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => item.Duration)
                    </td>
                    <td>
                        @Html.DisplayFor(entryItem => tables)
                    </td>
                    <td>
                        <a asp-controller="Waiter" asp-action="OrderPage" asp-route-id="@item.OrderId"><i class="fas fa-edit"></i></a>
                    </td>
                </tr>
            }
        }
    </thead>


</table>

PSAPI_RestaurantSystem/Views/Waiter/OrderPage.cshtml
@model PSAPIRestaurantSystem.Models.Order

@{
    ViewData["Title"] = "Užsakymas";
}

<h1>Užsakymas Nr. @Model.OrderId</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManagedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManagedBy.Employee.User.Person.Name) @Html.DisplayFor(model => model.ManagedBy.Employee.User.Person.Surname)
        </dd>
    </dl>

    <p style="font-size:25px">Užsakyti patiekalai/gėrimai:
        <a asp-controller="Waiter" asp-action="AddOrderedMeal" asp-route-id="@Model.OrderId"><i style="color:forestgreen; margin-left:25px" class="fa fa-cart-plus 5x"></i></a>
        <a asp-controller="Waiter" asp-action="PayOrder" asp-route-id="@Model.OrderId"><i style="margin-left:25px" class="fa fa-credit-card 5x"></i></a>
        <a asp-controller="Waiter" asp-action="OrderDeleteForm" asp-route-id="@Model.OrderId"><i style="color:darkred;margin-left:25px" class="fa fa-trash 5x"></i></a>
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().MenuEntryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OrderedMeals.FirstOrDefault().Comment)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderedMeals)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MenuEntry.MenuEntryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Comment)
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |*@
    <a asp-action="OrderList">Atgal į užsakymus</a>
</div>